export const accounts = [
  {
    account_id: 'acc_001',
    item_id: 'item_001',
    name: 'Plaid Checking',
    official_name: 'Plaid Gold Standard 0% Interest Checking',
    type: 'depository',
    subtype: 'checking',
    mask: '0000',
    institution_name: 'First Platypus Bank',
  },
  {
    account_id: 'acc_002',
    item_id: 'item_001',
    name: 'Plaid Saving',
    official_name: 'Plaid Silver Standard 0.1% Interest Saving',
    type: 'depository',
    subtype: 'savings',
    mask: '1111',
    institution_name: 'First Platypus Bank',
  },
  {
    account_id: 'acc_003',
    item_id: 'item_001',
    name: 'Plaid Credit Card',
    official_name: 'Plaid Diamond 12.5% APR Interest Credit Card',
    type: 'credit',
    subtype: 'credit card',
    mask: '3333',
    institution_name: 'First Platypus Bank',
  },
];

export const transactions = [
  {
    transaction_id: 'txn_001',
    account_id: 'acc_001',
    date: '2026-05-20',
    amount: 12.5,
    merchant_name: 'Spotify',
    category: 'Entertainment',
    pending: false,
  },
  {
    transaction_id: 'txn_002',
    account_id: 'acc_001',
    date: '2026-05-19',
    amount: 89.4,
    merchant_name: 'Whole Foods Market',
    category: 'Food and Drink',
    pending: false,
  },
  {
    transaction_id: 'txn_003',
    account_id: 'acc_001',
    date: '2026-05-17',
    amount: 2.99,
    merchant_name: 'Starbucks',
    category: 'Food and Drink',
    pending: false,
  },
  {
    transaction_id: 'txn_004',
    account_id: 'acc_001',
    date: '2026-05-15',
    amount: 45.0,
    merchant_name: 'Shell',
    category: 'Travel',
    pending: false,
  },
  {
    transaction_id: 'txn_005',
    account_id: 'acc_001',
    date: '2026-05-14',
    amount: 1200.0,
    merchant_name: 'Employer Inc',
    category: 'Transfer',
    pending: false,
  },
  {
    transaction_id: 'txn_006',
    account_id: 'acc_003',
    date: '2026-05-21',
    amount: 54.72,
    merchant_name: 'Amazon',
    category: 'Shopping',
    pending: true,
  },
  {
    transaction_id: 'txn_007',
    account_id: 'acc_003',
    date: '2026-05-18',
    amount: 9.99,
    merchant_name: 'Netflix',
    category: 'Entertainment',
    pending: false,
  },
  {
    transaction_id: 'txn_008',
    account_id: 'acc_003',
    date: '2026-05-16',
    amount: 34.5,
    merchant_name: 'Uber Eats',
    category: 'Food and Drink',
    pending: false,
  },
  {
    transaction_id: 'txn_009',
    account_id: 'acc_002',
    date: '2026-05-10',
    amount: 500.0,
    merchant_name: 'Transfer',
    category: 'Transfer',
    pending: false,
  },
  {
    transaction_id: 'txn_010',
    account_id: 'acc_003',
    date: '2026-05-12',
    amount: 120.0,
    merchant_name: 'Best Buy',
    category: 'Shopping',
    pending: false,
  },
];
